environment:
  COVERALLS_REPO_TOKEN:
    secure: +hgrWh6vwfA7rQRwEGfD0od5TBGW/jPEyGwy2jlBM4vZrtjNwnwaa9IzCrig5A+6
  STRONG_NAME_SECRET:
    secure: 4W8bFbUP7bJsxCqGF6+xfy7kCUjQscJcrGmjegVxxBs=
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" nuget install secure-file -ExcludeVersion
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" secure-file\tools\secure-file -decrypt Natsnudasoft.snk.enc -secret %STRONG_NAME_SECRET%
before_build:
  - nuget restore
build:
  project: Natsnudasoft.sln
  verbosity: minimal
test:
  assemblies: test\unit\NatsnudasoftTests\bin\Release\**\NatsnudasoftTests.dll
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: 'NatsnudaLibrary $(APPVEYOR_REPO_TAG_NAME)'
    description: ''
    auth_token:
      secure: winth2ckr0q/1fONK0Nz7MixzIikq4sYbi/uKfJ97WYgL6rKwI/TT9PNHXcX2pFF
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: IL1Xdk/t8SL1Dsjfw+pzzSjR7c3qBeydU+7ey4ObYVDaoHNUv+JDxrnxQZ8Im5+q
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
